{
	"name": "Matrixcreator",
    "speakableName": "Matrix creator",
	"version": "0.0.1",
    "icon": "fab fa-creative-commons-sampling",
	"author": "Psychokiller1888",
	"maintainers": [],
	"desc": "Access Matrix Creator sensors",
	"aliceMinVersion": "1.0.0",
	"pipRequirements": [
		"matrix-lite",
		"matrix-lite-nfc"
	],
	"systemRequirements":  [],
    "script": "matrixcreator.sh",
	"conditions": {
		"lang": [
			"en"
		]
	}
}
